version: "3.3"
services:
  ws:
    image: healthdao-pdf-processing:latest
    container_name: healthdao-pdf-processing
    build:
      context: ./python-langchain/
    networks:
      - ws
    ports:
      - "3000:3000"
    volumes:
      - ./python-langchain:/api
    mem_limit: 15G

networks:
    ws: