version: "3.3"
services:
  ws:
    image: healthdao-pdf-processing:latest
    container_name: healthdao-pdf-processing
    build:
      context: ./paddle/
    networks:
      - ws
    ports:
      - "3000:3000"
    volumes:
      - ./paddle:/api
    mem_limit: 15G
  langchain:
    image: healthdao-llm:latest
    container_name: healthdao-llm
    build:
      context: ./langchain/
      args:
        - USER_TYPE=${USER_TYPE:-node}
        - USER_ID=${USER_ID:-1001}
    networks:
      - ws
    ports:
      - "3001:3001"
    environment:
      - RUNNING_ENV=development
    volumes:
      - ./langchain:/api

networks:
    ws: