name: paddle
channels:
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=2.0.5
  - backcall=0.2.0
  - ca-certificates=2023.01.10
  - comm=0.1.2
  - debugpy=1.5.1
  - decorator=5.1.1
  - entrypoints=0.4
  - executing=0.8.3
  - ipykernel=6.19.2
  - ipython=8.8.0
  - jedi=0.18.1
  - jupyter_client=7.4.8
  - jupyter_core=5.1.1
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libsodium=1.0.18
  - libstdcxx-ng=11.2.0
  - matplotlib-inline=0.1.6
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - openssl=1.1.1t
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.0.1
  - platformdirs=2.5.2
  - prompt-toolkit=3.0.36
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.11.2
  - python=3.8.16
  - python-dateutil=2.8.2
  - pyzmq=23.2.0
  - readline=8.2
  - setuptools=66.0.0
  - six=1.16.0
  - sqlite=3.41.2
  - stack_data=0.2.0
  - tk=8.6.12
  - tornado=6.2
  - traitlets=5.7.1
  - wcwidth=0.2.5
  - wheel=0.38.4
  - xz=5.4.2
  - zeromq=4.3.4
  - zlib=1.2.13
  - pip:
    - anyio==3.6.2
    - astor==0.8.1
    - attrdict==2.0.1
    - babel==2.12.1
    - bce-python-sdk==0.8.83
    - bcrypt==4.0.1
    - beautifulsoup4==4.12.2
    - blinker==1.6.2
    - brotli==1.0.9
    - cachetools==5.3.0
    - certifi==2023.5.7
    - cffi==1.15.1
    - click==8.1.3
    - contextlib2==21.6.0
    - contourpy==1.0.7
    - cryptography==40.0.2
    - cssselect==1.2.0
    - cssutils==2.6.0
    - cycler==0.11.0
    - cython==0.29.34
    - et-xmlfile==1.1.0
    - exceptiongroup==1.1.1
    - execnet==1.9.0
    - fastapi==0.95.1
    - ffmpy==0.3.0
    - fire==0.5.0
    - flask==2.3.2
    - flask-babel==3.1.0
    - flask-cors==3.0.10
    - Flask-SocketIO==5.2.0
    - Flask-Session==0.4.*
    - python-engineio==4.3.3
    - python-socketio==5.7.1
    - fonttools==4.39.4
    - fsspec==2023.5.0
    - future==0.18.3
    - eventlet==0.30.2
    - gevent==22.10.2
    - geventhttpclient==2.0.2
    - gradio==3.11.0
    - gunicorn==20.1.0
    - greenlet==2.0.2
    - grpcio==1.54.0
    - h11==0.12.0
    - httpcore==0.15.0
    - httpx==0.24.0
    - idna==3.4
    - imageio==2.28.1
    - imgaug==0.4.0
    - importlib-metadata==6.6.0
    - importlib-resources==5.12.0
    - iniconfig==2.0.0
    - itsdangerous==2.1.2
    - jinja2==3.1.2
    - kiwisolver==1.4.4
    - lazy-loader==0.2
    - linkify-it-py==2.0.2
    - lmdb==1.4.1
    - lxml==4.9.2
    - markdown-it-py==2.2.0
    - markupsafe==2.1.2
    - matplotlib==3.7.1
    - mdit-py-plugins==0.3.5
    - mdurl==0.1.2
    - mock==5.0.2
    - mpmath==1.3.0
    - networkx==3.1
    - numpy==1.24.3
    - onnx
    - opencv-contrib-python-headless==4.6.0.66
    - opencv-python-headless==4.6.0.66
    - openpyxl==3.1.2
    - opt-einsum==3.3.0
    - orjson==3.8.12
    - packaging==23.1
    - paddle-bfloat==0.1.7
    - paddle2onnx==1.0.6
    - paddleocr==2.6.1.3
    - paddlepaddle
    - pandas==2.0.1
    - paramiko==3.1.0
    - path==16.6.0
    - path-py==12.5.0
    - pdf2docx==0.5.6
    - pdf2image==1.16.3
    - pillow==9.5.0
    - pluggy==1.0.0
    - premailer==3.10.0
    - protobuf
    - psutil==5.9.5
    - pyclipper==1.3.0.post4
    - pycparser==2.21
    - pycryptodome==3.17
    - pydantic==1.10.7
    - pydub==0.25.1
    - pymupdf==1.20.2
    - pynacl==1.5.0
    - pyparsing==3.0.9
    - pytest==7.3.1
    - pytest-shutil==1.7.0
    - python-docx==0.8.11
    - python-multipart==0.0.6
    - python-rapidjson==1.10
    - pytz==2023.3
    - pywavelets==1.4.1
    - pyyaml==6.0
    - rapidfuzz==3.0.0
    - rarfile==4.0
    - requests==2.30.0
    - scikit-image==0.20.0
    - scipy==1.9.1
    - shapely==2.0.1
    - sniffio==1.3.0
    - soupsieve==2.4.1
    - starlette==0.26.1
    - sympy==1.12
    - termcolor==2.3.0
    - tifffile==2023.4.12
    - tomli==2.0.1
    - tritonclient==2.33.0
    - typing-extensions==4.5.0
    - tzdata==2023.3
    - uc-micro-py==1.0.2
    - urllib3==2.0.2
    - uvicorn==0.22.0
    - visualdl==2.5.2
    - websockets==11.0.3
    - werkzeug==2.3.4
    - x2paddle==1.4.1
    - zipp==3.15.0
    - zope-event==4.6
    - zope-interface==6.0
